# üö¶ RELAT√ìRIO DE VIS√ÉO COMPUTACIONAL - PLACAS DE SINALIZA√á√ÉO

## üìÖ Data de Gera√ß√£o: 2025-08-29 01:13:46
## üìä Estat√≠sticas Gerais
- **Total de imagens**: 7
- **Imagens processadas com sucesso**: 0
- **Total de placas detectadas**: 0
- **Confian√ßa m√©dia**: 0.00

## üîç DETALHES POR IMAGEM


### ‚ùå sinalizacao/sinal 2.jpg
**Erro**: Erro ao processar sinalizacao/sinal 2.jpg: OpenCV(4.10.0) /Users/xperience/GHA-Actions-OpenCV/_work/opencv-python/opencv-python/opencv/modules/imgproc/src/clahe.cpp:353: error: (-215:Assertion failed) _src.type() == CV_8UC1 || _src.type() == CV_16UC1 in function 'apply'



### ‚ùå sinalizacao/sinal 3.jpg
**Erro**: Erro ao processar sinalizacao/sinal 3.jpg: OpenCV(4.10.0) /Users/xperience/GHA-Actions-OpenCV/_work/opencv-python/opencv-python/opencv/modules/imgproc/src/clahe.cpp:353: error: (-215:Assertion failed) _src.type() == CV_8UC1 || _src.type() == CV_16UC1 in function 'apply'



### ‚ùå sinalizacao/sinal 1.jpg
**Erro**: Erro ao processar sinalizacao/sinal 1.jpg: OpenCV(4.10.0) /Users/xperience/GHA-Actions-OpenCV/_work/opencv-python/opencv-python/opencv/modules/imgproc/src/clahe.cpp:353: error: (-215:Assertion failed) _src.type() == CV_8UC1 || _src.type() == CV_16UC1 in function 'apply'



### ‚ùå sinalizacao/sinal 4.jpg
**Erro**: Erro ao processar sinalizacao/sinal 4.jpg: OpenCV(4.10.0) /Users/xperience/GHA-Actions-OpenCV/_work/opencv-python/opencv-python/opencv/modules/imgproc/src/clahe.cpp:353: error: (-215:Assertion failed) _src.type() == CV_8UC1 || _src.type() == CV_16UC1 in function 'apply'



### ‚ùå sinalizacao/sinal 5.jpg
**Erro**: Erro ao processar sinalizacao/sinal 5.jpg: OpenCV(4.10.0) /Users/xperience/GHA-Actions-OpenCV/_work/opencv-python/opencv-python/opencv/modules/imgproc/src/clahe.cpp:353: error: (-215:Assertion failed) _src.type() == CV_8UC1 || _src.type() == CV_16UC1 in function 'apply'



### ‚ùå sinalizacao/sinal 7.jpg
**Erro**: Erro ao processar sinalizacao/sinal 7.jpg: OpenCV(4.10.0) /Users/xperience/GHA-Actions-OpenCV/_work/opencv-python/opencv-python/opencv/modules/imgproc/src/clahe.cpp:353: error: (-215:Assertion failed) _src.type() == CV_8UC1 || _src.type() == CV_16UC1 in function 'apply'



### ‚ùå sinalizacao/sinal 6.jpg
**Erro**: Erro ao processar sinalizacao/sinal 6.jpg: OpenCV(4.10.0) /Users/xperience/GHA-Actions-OpenCV/_work/opencv-python/opencv-python/opencv/modules/imgproc/src/clahe.cpp:353: error: (-215:Assertion failed) _src.type() == CV_8UC1 || _src.type() == CV_16UC1 in function 'apply'


